set -g mouse on

# Allow switching windows with shift + arrows
bind -n S-Left  previous-window
bind -n S-Right next-window

# Style the status bar
set -g status-style bg=black,fg=white
set -g window-status-current-style bg=blue,fg=white,bold

set -g status-right "#[fg=green]Solas Trace Engine #[fg=white]| %H:%M"
