FROM golang:1.24-alpine AS build
RUN go install github.com/pressly/goose/v3/cmd/goose@v3.24.1

FROM alpine:3.21
COPY --from=build /go/bin/goose /usr/local/bin/goose
COPY infrastructure/clickhouse/migrations /migrations
ENTRYPOINT ["goose", "-dir", "/migrations", "clickhouse"]
CMD ["up"]
